<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="13.3.5" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsAspireHost>true</IsAspireHost>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aaron.Akka.Aspire.Hosting" />
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.Redis" />
    <PackageReference Include="MessagePack" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Akka.CustomJobScheduling\Akka.CustomJobScheduling.csproj" />
    <ProjectReference Include="..\Akka.CustomJobScheduling.Api\Akka.CustomJobScheduling.Api.csproj" />
  </ItemGroup>

</Project>
